version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
    open-pull-requests-limit: 5
    cooldown:
      default-days: 3

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
    open-pull-requests-limit: 5
    cooldown:
      default-days: 3
    groups:
      patch-and-minor:
        update-types:
          - patch
          - minor
